### ISSUE TITLE
Hackerangriff  #1,2,3, ich bin drin 

### ISSUE THREAD

**Issue by BelmontR** [adamane/schule-zusammenfassungen#5]
Ich habe den Einladungslink zu deinem Repository auf die Männertoilette am Hauptbahnhof, mit der Unterschrift "Kommt vorbei für ne gute Zeit, Happy End und Freibier" geschrieben. 

Ist vlt. ne Sicherheitslücke.

**Comment by adamane** [comment]
Digi. 😂
